# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='chess',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ngame.proto\x12\x05\x63hess\"\xae\x01\n\nBoardProto\x12\x11\n\tbitboards\x18\x01 \x03(\x06\x12\x12\n\nen_passant\x18\x02 \x01(\x06\x12\x17\n\x0fhalf_move_count\x18\x03 \x01(\x05\x12\x19\n\x11no_progress_count\x18\x04 \x01(\x05\x12\x16\n\x0elast_move_from\x18\x05 \x01(\x05\x12\x14\n\x0clast_move_to\x18\x06 \x01(\x05\x12\x17\n\x0f\x63\x61stling_rights\x18\x07 \x03(\x06\";\n\tMoveProto\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x14\n\tpromotion\x18\x03 \x01(\x05:\x01\x34\"T\n\nGameRecord\x12-\n\x07players\x18\x03 \x03(\x0e\x32\x1c.chess.GameRecord.PlayerType\"\x17\n\nPlayerType\x12\t\n\x05HUMAN\x10\x00')
)



_GAMERECORD_PLAYERTYPE = _descriptor.EnumDescriptor(
  name='PlayerType',
  full_name='chess.GameRecord.PlayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HUMAN', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=320,
  serialized_end=343,
)
_sym_db.RegisterEnumDescriptor(_GAMERECORD_PLAYERTYPE)


_BOARDPROTO = _descriptor.Descriptor(
  name='BoardProto',
  full_name='chess.BoardProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bitboards', full_name='chess.BoardProto.bitboards', index=0,
      number=1, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='en_passant', full_name='chess.BoardProto.en_passant', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='half_move_count', full_name='chess.BoardProto.half_move_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no_progress_count', full_name='chess.BoardProto.no_progress_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_move_from', full_name='chess.BoardProto.last_move_from', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_move_to', full_name='chess.BoardProto.last_move_to', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='castling_rights', full_name='chess.BoardProto.castling_rights', index=6,
      number=7, type=6, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=196,
)


_MOVEPROTO = _descriptor.Descriptor(
  name='MoveProto',
  full_name='chess.MoveProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='chess.MoveProto.from', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='chess.MoveProto.to', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='promotion', full_name='chess.MoveProto.promotion', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=257,
)


_GAMERECORD = _descriptor.Descriptor(
  name='GameRecord',
  full_name='chess.GameRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='chess.GameRecord.players', index=0,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAMERECORD_PLAYERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=343,
)

_GAMERECORD.fields_by_name['players'].enum_type = _GAMERECORD_PLAYERTYPE
_GAMERECORD_PLAYERTYPE.containing_type = _GAMERECORD
DESCRIPTOR.message_types_by_name['BoardProto'] = _BOARDPROTO
DESCRIPTOR.message_types_by_name['MoveProto'] = _MOVEPROTO
DESCRIPTOR.message_types_by_name['GameRecord'] = _GAMERECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoardProto = _reflection.GeneratedProtocolMessageType('BoardProto', (_message.Message,), dict(
  DESCRIPTOR = _BOARDPROTO,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:chess.BoardProto)
  ))
_sym_db.RegisterMessage(BoardProto)

MoveProto = _reflection.GeneratedProtocolMessageType('MoveProto', (_message.Message,), dict(
  DESCRIPTOR = _MOVEPROTO,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:chess.MoveProto)
  ))
_sym_db.RegisterMessage(MoveProto)

GameRecord = _reflection.GeneratedProtocolMessageType('GameRecord', (_message.Message,), dict(
  DESCRIPTOR = _GAMERECORD,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:chess.GameRecord)
  ))
_sym_db.RegisterMessage(GameRecord)


# @@protoc_insertion_point(module_scope)
